<h1 style = color:blue; >Mali fudbal</h1>
<h3>Prikaži rezultate mečeva!</h3><br><br>

<?php // last match ID
    $sql_select_num_match = "SELECT game_id FROM matches ORDER BY game_id DESC;";
    if ($result = mysqli_query($conn2, $sql_select_num_match)) {
        if (mysqli_num_rows($result) > 0) {
            $row = mysqli_fetch_array($result);
            $row['game_id'] . '.';
            $last_match_id = $row['game_id'];
        }
    }
?>
        
<form action="index.php?page=futsal" method="post">
    <label>Odaberi kolo:</label>
    <select name="game_id_input">
        <optgroup label="Sva kola od 1. do <?= $last_match_id ?>.">

            <?php
                $sql_select_match = "SELECT DISTINCT game_id FROM matches";
                if ($result = mysqli_query($conn2, $sql_select_match)) {
                    if (mysqli_num_rows($result) > 0) {
                        while ($row = mysqli_fetch_array($result)) {
                            echo '<option value="' . $row['game_id'] . '">' . $row['game_id'] . '. Kolo' . '</option>';
                        }
                    }
                }
            ?>
        </optgroup>
    </select>
    <br>
    <input type="hidden" name="action" value="showMatch">
    <input type="submit" value="submit">
</form>

<br><br><br><br>

<h3>Prikaži listu najboljih strelaca!</h3><br><br>

<form action="index.php?page=futsal" method="post">
    <label>Odaberi kolo:</label>
    <select name="game_id_input">
        <optgroup label="Sva kola od 1. do <?= $last_match_id ?>.">

            <?php
                $sql_select_match = "SELECT DISTINCT game_id FROM matches";
                if ($result = mysqli_query($conn2, $sql_select_match)) {
                    if (mysqli_num_rows($result) > 0) {
                        while ($row = mysqli_fetch_array($result)) {
                            echo '<option value="' . $row['game_id'] . '">' . $row['game_id'] . '. Kolo' . '</option>';
                        }
                    }
                }
            ?>
        </optgroup>
    </select>
    <br>
    <input type="hidden" name="action" value="showMatch">
    <input type="submit" value="submit">
</form>

<br><br><br><br>

<h3>Prikaži igrača!</h3><br><br>

<form action="index.php?page=futsal" method="post">
    <label>Odaberi kolo:</label>
    <select name="game_id_input">
        <optgroup label="Sva kola od 1. do <?= $last_match_id ?>.">

            <?php
                $sql_select_match = "SELECT DISTINCT game_id FROM matches";
                if ($result = mysqli_query($conn2, $sql_select_match)) {
                    if (mysqli_num_rows($result) > 0) {
                        while ($row = mysqli_fetch_array($result)) {
                            echo '<option value="' . $row['game_id'] . '">' . $row['game_id'] . '. Kolo' . '</option>';
                        }
                    }
                }
            ?>
        </optgroup>
    </select>
    <br>
    <input type="hidden" name="action" value="showMatch">
    <input type="submit" value="submit">
</form>
