<div class="content-container">
<h1 style = color:blue; >Friday 13th Calculator !</h1>
<h3>Please enter the 'start year' and 'end year'!</h3><br><br>

<form action="index.php?page=friday" method="post">
    <input type="number" name='startYear' placeholder="Start Year"><br>
    <input type="number" name='endYear' placeholder="End Year"><br>
    <input type="submit" name="submit_button" value="Submit"/><br><br>
</form>
</div>
