<div class="content-container">
<h1 style = color:blue; >Friday 13th Calculator !</h1>
<h3>Please choose the day and range of years!</h3><br><br>

<form action="index.php?page=friday" method="post">
    <select name="day_week">
        <optgroup label="Choose the day">
            <?php
                $days = array('Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday');
                for ($i = 0; $i <= count($days) - 1; $i++) { 
                    echo "<option>" . $days[$i] . "</option>";
                }
            ?>
        </optgroup>
    </select><br>

    <select name="day_num">
        <optgroup label="Choose the day">
            <?php
                for ($i = 1; $i <= 31; $i++) { 
                    echo "<option>$i</option>";
                }
            ?>
        </optgroup>
    </select><br>

    <select name="year1">
        <optgroup label="Choose the start year">
            <?php
                for ($i = date('Y'); $i >= 1900; $i--) { 
                    echo "<option>$i</option>";
                }
            ?>
        </optgroup>
    </select>

    <br>

    <select name="year2">
        <optgroup label="Choose the end year">
            <?php
                for ($i = date('Y'); $i >= 1900; $i--) { 
                    echo "<option>$i</option>";
                }
            ?>
        </optgroup>
    </select><br>

    <input type="submit" name="submit_button" value="Submit"/><br><br>
</form>

<br><br><br>

<!-- <form action="index.php?page=friday" method="post">
    <input type="number" name='startYear' placeholder="Start Year"><br>
    <input type="number" name='endYear' placeholder="End Year"><br>
    <input type="submit" name="submit_button" value="Submit"/><br><br>
</form> -->
</div>
