<h1 style = color:blue; >Table Football !</h1>
<h3>Please fill out the form!</h3><br><br>

<form action="index.php?page=tablefootball" method="post" onsubmit="openTab(event,'newPlayer')">
    <input type="text" name="first" placeholder="First name"><br>
    <input type="text" name="last" placeholder="Last name"><br>
    <input type="text" name="nick" placeholder="Nick name"><br>
    <input type="hidden" name="action" value="addPlayer">
    <input type="submit" value="submit"><br><br>
</form>
