<form action="index.php?page=futsal" method="post">
    <br>
    <h3>Dodaj igrače:</h3>
    <label>Tim 1:</label>
    <br>
        <select name="team_1[]" multiple>
            <optgroup label="Svi igrači">
            <?php
                $sql_select_match = "SELECT first_name, last_name, g.player_id, p.player_id AS pp_id, team_id FROM players p
                LEFT JOIN live_game g ON p.player_id = g.player_id
                WHERE team_id IS NULL
                ORDER BY first_name";
                    if ($result = mysqli_query($conn2, $sql_select_match)) {
                        if (mysqli_num_rows($result) > 0) {
                            while ($row = mysqli_fetch_array($result)) {
                                echo '<option value="' . $row['pp_id'] . '">' .  $row['first_name']. ' ' . $row['last_name']. '</option>';
                            }
                        }
                    }
                ?>
            </optgroup>
        </select>
    <br><br>
    
    <input type="hidden" name="action" value="add_player">
    <input type="hidden" name="team" value="team_1">
    <input type="submit" value="submit">
    </form>

    <form action="index.php?page=futsal" method="post">
    <br>
    <label>Tim 2:</label>
    <br>
        <select name="team_2[]" multiple>
            <optgroup label="Svi igrači">
                <?php
                    $sql_select_match = "SELECT first_name, last_name, g.player_id, p.player_id AS pp_id, team_id FROM players p
                    LEFT JOIN live_game g ON p.player_id = g.player_id
                    WHERE team_id IS NULL -- select players who aren't in a team
                    ORDER BY first_name";
                        if ($result = mysqli_query($conn2, $sql_select_match)) {
                            if (mysqli_num_rows($result) > 0) {
                                while ($row = mysqli_fetch_array($result)) {
                                    echo '<option value="' . $row['pp_id'] . '">' .  $row['first_name']. ' ' . $row['last_name']. '</option>';
                                }
                            }
                        }
                ?>
            </optgroup>
        </select>
    <br><br>

    <input type="hidden" name="action" value="add_player">
    <input type="hidden" name="team" value="team_2">
    <input type="submit" value="submit">
</form>


<br><br>

