<form action="index.php?page=futsal" method="post">
    <br>
    <h3>Dodaj igrače:</h3>
    <label>Tim 1:</label>
    <br>
    <select name="team_1[]" multiple>
        <optgroup label="Svi igrači">
        <?php
            $sql_select_match = "SELECT * FROM players ORDER BY first_name";
                if ($result = mysqli_query($conn2, $sql_select_match)) {
                    if (mysqli_num_rows($result) > 0) {
                        while ($row = mysqli_fetch_array($result)) {
                            if ($row['player_id'] != 2) {
                            echo '<option value="' . $row['player_id'] . '">' . $row['first_name']. ' ' . $row['last_name']. '</option>';
                        }
                        }
                    }
                }
            ?>
        </optgroup>
    </select>
    <br><br>
    
    <input type="hidden" name="action" value="add_or_remove_player">
    <input type="hidden" name="team" value="team_1">
    <input type="radio" name="player" value="add_player" checked>
    <label>Dodaj igrača</label><br>
    <input type="radio" name="player" value="remove_player">
    <label>Ukloni igrača</label><br>
    <input type="submit" value="submit">
    </form>


    <form action="index.php?page=futsal" method="post">
    <br>
    <label>Tim 2:</label>
    <br>
    <select name="team_2[]" multiple>
        <optgroup label="Svi igrači">
            <?php
                $sql_select_match = "SELECT * FROM players ORDER BY first_name";
                    if ($result = mysqli_query($conn2, $sql_select_match)) {
                        if (mysqli_num_rows($result) > 0) {
                            while ($row = mysqli_fetch_array($result)) {
                                echo '<option value="' . $row['player_id'] . '">' . $row['first_name']. ' ' . $row['last_name']. '</option>';
                            }
                        }
                    }
            ?>
        </optgroup>
    </select>
    <br><br>

    <input type="hidden" name="action" value="add_or_remove_player">
    <input type="hidden" name="team" value="team_2">
    <input type="radio" name="player" value="add_player" checked>
    <label>Dodaj igrača</label><br>
    <input type="radio" name="player" value="remove_player">
    <label>Ukloni igrača</label><br>
    <input type="submit" value="submit">
</form>


<br><br>





