
<div class="players">
    <h3>TIM 1</h3>
    <form class="players">
        <select class="unselected_players" id="1" multiple onchange="insert_player_into_live_game_table(this.value, this.id);">
            <optgroup label="Svi igrači"></optgroup>
        </select>
    </form>
</div>

<br><br>

<div class="players">
    <h3>TIM 2</h3>
    <form class="players">
        <select class="unselected_players" id="2" multiple onchange="insert_player_into_live_game_table(this.value, this.id);">
            <optgroup label="Svi igrači"></optgroup>
        </select>
    </form>
</div>

<br><br><br><br>

<h3 style="position: absolute; top: 150px; right: 900px">TIM 1</h3>
<div id="team_1" style="position: absolute; top: 200px; right: 300px">
    <table id="table_1">
        <thead id="thead_1"></thead>
        <tbody id="tbody_1"></tbody>
    </table>
</div>

<br><br><br><br>

<h3 style="position: absolute; top: 450px; right: 900px">TIM 2</h3>
<div id="team_2" style="position: absolute; top: 500px; right: 300px">
    <table id="table_2">
        <thead id="thead_2"></thead>
        <tbody id="tbody_2"></tbody>
    </table>
</div>
