<div class="content-container">
    <div class="form-container">
                <div class="form-input">
                    <?php include 'databases/mali_Fudbal_DB.php'; ?>
                    <?php include $form; ?>
                </div>
                <div class="echo-result">
                    <?php include 'databases/mali_Fudbal_DB.php'; ?>
                    <?php include $echo; ?>
                </div>            
    </div>
</div>
