<footer>
    <ul>
        <li><p>Author: Milan Ivic</p></li>
        <li><p><a href="mailto:milanivic1995@gmail.com">milanivic1995@gmail.com</a></p></li>
        <li><p>&copy; All rights reserved</p></li>
  </ul>
</footer>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>

<script>
function openTab(evt, tabName) {
  var i, x, tablinks;
  x = document.getElementsByClassName("tab");
  for (i = 0; i < x.length; i++) {
    x[i].style.display = "none";
  }
  tablinks = document.getElementsByClassName("tablink");
  for (i = 0; i < x.length; i++) {
    tablinks[i].className = tablinks[i].className.replace(" active", "");
  }
  document.getElementById(tabName).style.display = "block";
  evt.currentTarget.className += " active";

}

var count = 2;
$("#new_count").click(function() {
  count += 2;
  $("#players_t1").load("Futsal/new_match/echo.php", {
    new_count: count
  });
})


</script>
</body>
</html>
