<?php

switch ($page) {
    case 'age':
        $title = 'Age Calculator';
        break;

    case 'friday':
        $title = 'Friday the 13th Calculator';
        break;

    case 'birthday':
        $title = 'Birthday Counter';
        break;

    case 'tablefootball':
        $title = 'Table Football';
        break;

    case 'futsal':
        $title = 'Futsal';
        break;

    case 'searchtool':
        $title = 'Search Tool';
        break;
    
    default:
        $title = 'Multicalculator';
        break;
}

?>

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="css.css">
    <title><?= $title ?></title>
    <script defer src="js.js"></script>
</head>
<body class="<?= ($page == 'tablefootball') ? 'table_football_background' : '' ?>">
