<header>
        <ul>
        <li class="<?= ($page == 'friday') ? 'active' : '' ?>"><a href="index.php?page=friday">Friday the 13th Calculator</a></li>
        <li class="<?= ($page == 'age') ? 'active' : '' ?>"><a href="index.php?page=age">Age Calculator</a></li>
        <li class="<?= ($page == 'birthday') ? 'active' : '' ?>"><a href="index.php?page=birthday">Birthday Counter</a></li>
        <li class="<?= ($page == 'tablefootball') ? 'active' : '' ?>"><a href="index.php?page=tablefootball">Table Football</a></li>
        <li class="<?= ($page == 'futsal') ? 'active' : '' ?>"><a href="index.php?page=futsal">Futsal</a></li>
        <li class="<?= ($page == 'searchtool') ? 'active' : '' ?>"><a href="index.php?page=searchtool">Search Tool</a></li>
        </ul>
</header>
