<div class="content-container">
    
    <div class="table-tabs">
        <div class="tab-style tablink active" onclick="openTab(event, 'statistics')">Statistika</div>
        <div class="tab-style tablink" onclick="openTab(event, 'new_match')">Novi meč</div>
    </div>
    
    <div id="statistics" class="w3-container w3-border tab" style="display: block;">
        <div class="form-container">
            <div class="form-input">
                <?php include $form_statistics; ?>
                <?php include $form_statistics_2; ?>
            </div>

        </div>
    </div>

    <div id="new_match" class="w3-container w3-border tab" style="display: none;"> 
        <div class="form-container">
            <div class="form-input">
                <!-- include $form_new_match; -->
                <?php include $form_new_match_2; ?>
            </div>

        </div>
    </div>

</div>
