<div class="content-container">
    
    <div class="w3-bar w3-black">
        <button class="w3-bar-item w3-button tablink w3-red" onclick="openCity(event,'newPlayer')">New Player</button>
        <button class="w3-bar-item w3-button tablink" onclick="openCity(event,'showScore')">Show Score</button>
        <button class="w3-bar-item w3-button tablink" onclick="openCity(event,'insertScore')">Insert Score</button>
    </div>
    
    <div id="newPlayer" class="w3-container w3-border city">
        <div class="form-container">
            <div class="form-input">
                <?php include 'TableFootball/newPlayer/form.phtml'; ?>
            </div>
            <div class="echo-result">
                <?php include 'TableFootball/tableFootball.php'; ?>
                <?php include 'TableFootball/newPlayer/echo.php'; ?>
            </div>
        </div>
    </div>

    <div id="showScore" class="w3-container w3-border city" style="display:none"> 
        <div class="form-container">
            <div class="form-input">
                <?php include 'TableFootball/showScore/form.phtml'; ?>
            </div>
            <div class="echo-result">
                <?php include 'TableFootball/tableFootball.php'; ?>
                <?php include 'TableFootball/showScore/echo.php'; ?>
            </div>
        </div>
    </div>

    <div id="insertScore" class="w3-container w3-border city" style="display:none"> 
        <div class="form-container">
            <div class="form-input">
                <?php include 'TableFootball/insertScore/form.phtml'; ?>
            </div>
            <div class="echo-result">
                <?php include 'TableFootball/tableFootball.php'; ?>
                <?php include 'TableFootball/insertScore/echo.php'; ?>
            </div>
        </div>
    </div>

</div>
