<div class="content-container">
    
    <div class="table-tabs">
        <div class="tab-style tablink active" onclick="openTab(event,'newPlayer')">New Player</div>
        <div class="tab-style tablink" onclick="openTab(event,'showScore')">Show Score</div>
        <div class="tab-style tablink" onclick="openTab(event,'insertScore')">Insert Score</div>
    </div>
    
    <div id="newPlayer" class="w3-container w3-border tab">
        <div class="form-container">
            <div class="form-input">
                <?php include 'TableFootball/newPlayer/form.phtml'; ?>
            </div>
            <div class="echo-result">
                <?php include 'TableFootball/tableFootball.php'; ?>
                <?php include 'TableFootball/newPlayer/echo.php'; ?>
            </div>
        </div>
    </div>

    <div id="showScore" class="w3-container w3-border tab" style="display:none"> 
        <div class="form-container">
            <div class="form-input">
                <?php include 'TableFootball/showScore/form.phtml'; ?>
            </div>
            <div class="echo-result">
                <?php include 'TableFootball/tableFootball.php'; ?>
                <?php include 'TableFootball/showScore/echo.php'; ?>
            </div>
        </div>
    </div>

    <div id="insertScore" class="w3-container w3-border tab" style="display:none"> 
        <div class="form-container">
            <div class="form-input">
                <?php include 'TableFootball/insertScore/form.phtml'; ?>
            </div>
            <div class="echo-result">
                <?php include 'TableFootball/tableFootball.php'; ?>
                <?php include 'TableFootball/insertScore/echo.php'; ?>
            </div>
        </div>
    </div>

</div>
