<div class="content-container">
    
    <div class="table-tabs">
        <div class="tab-style tablink active" onclick="openTab(event, 'newplayer')">New Player</div>
        <div class="tab-style tablink" onclick="openTab(event, 'showscore')">Show Score</div>
        <div class="tab-style tablink" onclick="openTab(event, 'insertscore')">Insert Score</div>
    </div>
    
    <div id="newplayer" class="w3-container w3-border tab" style="display: block;">
        <div class="form-container">
            <div class="form-input">
                <?php include 'TableFootball/newPlayer/form.phtml'; ?>
            </div>
            <div class="echo-result">
                <?php include 'databases/table_Football_DB.php'; ?>
                <?php include 'TableFootball/newPlayer/echo.php'; ?>
            </div>
        </div>
    </div>

    <div id="showscore" class="w3-container w3-border tab" style="display: none;"> 
        <div class="form-container">
            <div class="form-input">
                <?php include 'TableFootball/showScore/form.phtml'; ?>
            </div>
            <div class="echo-result">
                <?php include 'databases/table_Football_DB.php'; ?>
                <?php include 'TableFootball/showScore/echo.php'; ?>
            </div>
        </div>
    </div>

    <div id="insertscore" class="w3-container w3-border tab" style="display: none;"> 
        <div class="form-container">
            <div class="form-input">
                <?php include 'TableFootball/insertScore/form.phtml'; ?>
            </div>
            <div class="echo-result">
                <?php include 'databases/table_Football_DB.php'; ?>
                <?php include 'TableFootball/insertScore/echo.php'; ?>
            </div>
        </div>
    </div>

</div>
