<h1 style = color:blue; >Table Football !</h1>
<h3>Please fill out the form!</h3><br><br>

<form action="index.php?page=tablefootball" method="post">
    <input type="number" name="id" placeholder="ID"><br>
    <input type="number" name="win" placeholder="Matches won"><br>
    <input type="number" name="loss" placeholder="Matches lost"><br>
    <input type="hidden" name="action" value="updateScore">
    <input type="submit" value="submit"><br><br>
</form>
