<h1 style = color:blue; >Table Football !</h1>
<h3>Please fill out the form!</h3><br><br>

<form action="index.php?page=tablefootball" method="post">
    <input type="text" name="player_nick1" placeholder="Nick"><br>
    <input type="text" name="win1" placeholder="Matches won"><br><br>
    <input type="text" name="player_nick2" placeholder="Nick"><br>
    <input type="text" name="win2" placeholder="Matches won "><br>
    <input type="hidden" name="action" value="insertScore">
    <input type="submit" value="submit"><br><br>
</form>
