<h1 style = color:blue; >Table Football !</h1>
<h3>Please fill out the form!</h3><br><br>

<form action="index.php?page=tablefootball" method="post">
    <p>First Player</p>
    <select name="first_player_id">
        <optgroup label='Choose Player'>
        <?php
            $sql_select_players = "SELECT * FROM players";
            if ($result = mysqli_query($conn, $sql_select_players)) {
                if (mysqli_num_rows($result) > 0) {
                    while ($row = mysqli_fetch_array($result)) {
                        echo '<option value="' . $row['player_id'] . '">' . $row['nick_name'] . '</option>';
                    }
                }
            }
        ?>
        </optgroup>
    </select>
    <input type="number" name="win1" min="0" max="10"><br><br>

    <p>Second Player</p>
    <select name="second_player_id">
        <optgroup label='Choose Player'>
        <?php
            $sql_select_players = "SELECT * FROM players";
            if ($result = mysqli_query($conn, $sql_select_players)) {
                if (mysqli_num_rows($result) > 0) {
                    while ($row = mysqli_fetch_array($result)) {
                        echo '<option value="' . $row['player_id'] . '">' . $row['nick_name'] . '</option>';
                    }
                }
            }
        ?>
        </optgroup>
    </select>
    <input type="number" name="win2" min="0" max="10"><br><br>
    <input type="hidden" name="action" value="insertScore">
    <input type="submit" value="submit"><br><br>
</form>
