<h3>Prikaži igrače!</h3><br><br>
<form>
    <select onchange="showUser(this.value)">
        <option value="">izaberi igraca</option>
        <?php
            $sql_select_player = "SELECT * FROM players
            ORDER BY first_name"
            ;
            if ($result = mysqli_query($conn2, $sql_select_player)) {
                if (mysqli_num_rows($result) > 0) {
                    while ($row = mysqli_fetch_array($result)) {
                        echo '<option value="' . $row['player_id'] . '">' . $row['first_name'] . ' ' . $row['last_name'] . '</option>';
                    }
                }
            }
        ?>
        </optgroup>
    </select>
    <br>
</form>
