<h3>Prikaži rezultate mečeva!</h3>
<form>
    <select onchange="showGame(this.value)">
        <option value="">Izaberi kolo</option>
        <?php
            $sql_select_match = "SELECT DISTINCT game_id FROM futsal_games"
            ;
            if ($result = mysqli_query($conn2, $sql_select_match)) {
                if (mysqli_num_rows($result) > 0) {
                    while ($row = mysqli_fetch_array($result)) {
                        echo '<option value="' . $row['game_id'] . '">' . $row['game_id'] . '. Kolo' . '</option>';
                    }
                }
            }
        ?>
    </select>
</form>

<div id="game_stats">
    <p style="font-style: italic;">Tabela će se prikazati ovde:</p>
</div>
<br>
