<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="style.css">
    <title><?php echo $title ?></title>
    <script defer src="js.js"></script>
</head>
<body>
<header>
        <ul>
        <li id="tab1" class="page active-link"><a href="friday13thPage.php">Friday the 13th Calculator</a></li>
        <li id="tab2" class="page"><a href="ageCalculatorPage.php">Age Calculator</a></li>
        <li id="tab3" class="page"><a href="birthdayCounterPage.php">Birthday Counter</a></li>
        <li><a>Services</a></li>
        <li><a>Contact Me</a></li>
        </ul>
</header>
<div class="sidebar">
<div class="sidebar-item">item 1</div>
<div class="sidebar-item">item 2</div>
<div class="sidebar-item">item 3</div>
<div class="sidebar-item">item 4</div>
<div class="sidebar-item">item 5</div>
</div>

<div class="content-container">
    <div class="form-container">
                <div class="form-input">
                    <?php include $form; ?>
                </div>
                <div class="echo-result">
                    <?php include $echo; ?>
                </div>            
    </div>
</div>

<footer>
    <ul>
        <li><p>Author: Milan Ivic</p></li>
        <li><p><a href="mailto:milanivic1995@gmail.com">milanivic1995@gmail.com</a></p></li>
        <li><p>&copy; All rights reserved</p></li>
  </ul>
</footer>
</body>
</html>