<h1 style = color:blue; >Birthday Counter !</h1>
<h3>Please enter your birthday!</h3><br><br>

<form action="index.php?page=birthday" method="post">
    <input type="number" name='year' placeholder='1987'><br>
    <input type="number" name='month' placeholder='12'><br>
    <input type="number" name='day' placeholder='31'><br><br>

    <input type="submit" name="submit_button" value="Submit"/><br><br>
</form>

<p>Current time and date:</p>

<!-- atribute required HTML -->

<?php

date_default_timezone_set("Europe/Belgrade");
echo date("H:i:s"). "<br>";
echo date("d/M/Y"). "<br><br>";
?>
