<h1 style = color:blue; >Table Football !</h1>
<h3>Please fill out the form!</h3><br><br>

<form action="index.php?page=tablefootball" method="post" onsubmit="openTab(event,'showScore')">
    <input type="text" name="player_nick_or_id_1" placeholder="nick or ID"><br>
    <input type="text" name="player_nick_or_id_2" placeholder="nick or ID"><br>
    <input type="text" name="date1" placeholder="yyyy-mm-dd"><br>
    <input type="text" name="date2" placeholder="yyyy-mm-dd"><br>
    <input type="radio" name="score" value="separate" checked>
    <label for="separate">Score separated by dates</label><br>
    <input type="radio" name="score" value="sum">
    <label for="sum">Summarized score</label><br>
    <input type="hidden" name="action" value="showScore">
    <input type="submit" value="submit"><br><br>
</form>


