<h1 style = color:blue; >Table Football !</h1>
<h3>Please fill out the form!</h3><br><br>

<!-- Select tag with players from players table -->




<form action="index.php?page=tablefootball" method="post">
<p>First Player</p>
<select name="first_player_id">
    <optgroup label='Choose Player'>
    <?php
        $sql_select_players = "SELECT * FROM players";
        if ($result = mysqli_query($conn, $sql_select_players)) {
            if (mysqli_num_rows($result) > 0) {
                while ($row = mysqli_fetch_array($result)) {
                    echo '<option value="' . $row['player_id'] . '">' . $row['nick_name'] . '</option>';
                }
            }
        }
    ?>
    </optgroup>
</select>

<p>Second Player</p>
<select name="second_player_id">
    <optgroup label='Choose Player'>
    <?php
        $sql_select_players = "SELECT * FROM players";
        if ($result = mysqli_query($conn, $sql_select_players)) {
            if (mysqli_num_rows($result) > 0) {
                while ($row = mysqli_fetch_array($result)) {
                    echo '<option value="' . $row['player_id'] . '">' . $row['nick_name'] . '</option>';
                }
            }
        }
    ?>
    </optgroup>
</select>
<br><br>
    <input type="text" name="date1" placeholder="yyyy-mm-dd"><br>
    <input type="text" name="date2" placeholder="yyyy-mm-dd"><br>
    <input type="radio" name="score" value="separate" checked>
    <label for="separate">Score separated by dates</label><br>
    <input type="radio" name="score" value="sum">
    <label for="sum">Summarized score</label><br>
    <input type="hidden" name="action" value="showScore">
    <input type="submit" value="submit"><br><br>
</form>

<!-- 
    bez obzira kojim redosledom unesemo playere tabela se na isti nacin prikazuje.
    ne moze se provaliti koja kolumna za kog igraca
-->
